name: Build Windows EXE

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Create executable
      run: |
        pyinstaller --onefile --windowed main.py  # حذف --icon و --add-data

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: SMS_Sender_App
        path: dist/main.exe
